### ISSUE TITLE
第一次进入相册后系统导航没有隐藏

### ISSUE THREAD

**Issue by mengwq** [RainManGO/ZYImagePickerAndBrower#1]
遇到一个很蛋疼的问题，不知道是我项目出的问题还是什么，第一次进入相册后系统导航没有隐藏，最后我在ZYBaseViewController 中的viewWillAppear 中调用setNavigationBarHidden这个方法才把系统的导航栏隐藏掉。接着又遇到一个新问题，点击返回按钮直接返回了我调用相册图片的那个界面，并没有返回选择相册的界面，然后我就看了backClick这个方法，作者加了一个判断，判断presentationController是否存在，让我纠结的是这个一直存在，没办法就直接删除那个dismiss方法,居然神奇的没出bug，所有问题都解决了

**Comment by RainManGO** [comment]
谢谢你提出的问题，我已经发现了这个bug。之前加presentationController判断，是因为有人push进来预览界面无法back，现在已经修复。
